# Generated by Django 4.0.6 on 2022-07-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0002_articulos_tienda_clientes_tienda_pedidos_tienda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes_tienda',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
